### PR TITLE
Fixed notes formik validation and signup redirection

### LINKED ISSUE #726: UI issues
@edwinbbu _a

- [ ] When adding title of note, the formik validation for description is being run, But it should only get run when we click `save changes` button.
- [ ] After signup, we are directly getting logged in - but we should only get redirected to login page

### PR DESCRIPTION
**Pull request by edwinbbu**
Fixes #726 

Changes
- Formik validation improvements in notes form
- Error toastr messages updated
- Redirected to the login page on successful signup.

Below toastr shown on successful signup.
Screenshot 2021-11-23 at 7 18 45 PM

### CODE REVIEW

File: app/javascript/src/apis/axios.js [hunk 1]
```diff
@@ -41,9 +41,9 @@ const handleSuccessResponse = response => {
 const handleErrorResponse = (error, authDispatch) => {
   if (error.response?.status === 401) {
     authDispatch({ type: "LOGOUT" });
-    Toastr.error({ error: error.response?.data?.error });
+    Toastr.error(error.response?.data?.error);
   } else {
-    Toastr.error({ error: error.response?.data?.error || error.message });
+    Toastr.error(error.response?.data?.error || error.message);
```
Comment (edwinbbu) [inline app/javascript/src/apis/axios.js:46]: Made this change in order to respect the changes done in PR https://github.com/bigbinary/neeto-ui/pull/634 in neetoui.

File: app/javascript/src/components/Dashboard/Notes/Pane/Form.jsx [hunk 2]
```diff
@@ -18,25 +20,33 @@ export default function NoteForm({ onClose, refetch, note, isEdit }) {
       refetch();
       onClose();
     } catch (err) {
-      Toastr.error(err);
+      logger.error(err);
```
Comment (edwinbbu) [inline app/javascript/src/components/Dashboard/Notes/Pane/Form.jsx:23]: Changed to logger since we are already catching the error and displaying Toastr in the axios response handler.

**Comment by edwinbbu** [comment]
@yedhink _a Please review.
